source "https://rubygems.org"

ruby "3.2.9"

# Rails
gem "rails", "~> 7.1.0"

# Database
gem "pg", "~> 1.5"

# Application server
gem "puma", ">= 5.0"

# JSON
gem "jbuilder"

# CORS
gem "rack-cors"

# Reduces boot times through caching
gem "bootsnap", require: false

# Security: Fix WEBrick vulnerability (CVE-2024-47220)
gem "webrick", ">= 1.8.2"

# Security: Fix Thor vulnerability
gem "thor", ">= 1.4.0"

group :development, :test do
  # Debugging
  gem "debug", platforms: %i[mri windows]

  # Testing
  gem "factory_bot_rails", "~> 6.4"
  gem "faker", "~> 3.2"
  gem "rspec-rails", "~> 6.1"

  # Linting
  gem "rubocop", "~> 1.59", require: false
  gem "rubocop-rails", "~> 2.23", require: false
  gem "rubocop-rspec", "~> 2.26", require: false
end

group :development do
  # Code reloading
  gem "spring"
  gem "spring-commands-rspec"
end

group :test do
  gem "database_cleaner-active_record", "~> 2.1"
  gem "shoulda-matchers", "~> 6.0"
  gem "simplecov", require: false
end
